- name: installing apache
  hosts: web
  become: yes
  tasks:  
    - name: installing web server apache
      ansible.builtin.dnf:
        name: httpd
        state: installed
    - name: start httpd server 
      ansible.builtin.service:
         name: httpd
         state: started
         enabled: yes    