- name: varibales from FILE
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
   - name: using variables from vars.yaml
     ansible.builtin.debug:
      msg: "my course is {{course}}, name is {{name}}, duration {{duration}}"
