- name: prompt variables
  hosts: web
  vars_prompt:
    - name: USERNAME
      prompt: enter name of user
      private: no
    - name: PASSWD
      prompt: enter password
      private: yes
  tasks:
   - name: using prompt variables
     ansible.builtin.debug:
     msg: "username is {{USERNAME}} && password is {{PASSWD}}"
