- name: conditional statements 
  hosts: web 
  become: yes
  tasks: 
  - name: using conditionals 
    ansible.builtin.command: id jyothi1
    register: USER_CHECK
    ignore_errors: true

  - name: print user-check information 
    ansible.builtin.debug:
     msg: "info is {{USER_CHECK}}"

  - name: creating user 
    ansible.builtin.command: useradd jyothi1 
    when: USER_CHECK.rc != 0 
     
  - name: printing message 
    ansible.builtin.debug:
      msg: "hello there!!"
  
  